CREATE TABLE "Staples"
(
    "Item Count" INTEGER NOT NULL,
    "Ship Priority" TEXT ENCODING DICT(32) NOT NULL,
    "Order Priority" TEXT ENCODING DICT(32) NOT NULL,
    "Order Status" TEXT ENCODING DICT(32) NOT NULL,
    "Order Quantity" DOUBLE NOT NULL,
    "Sales Total" DOUBLE NOT NULL,
    "Discount" DOUBLE NOT NULL,
    "Tax Rate" DOUBLE NOT NULL,
    "Ship Mode" TEXT ENCODING DICT(32) NOT NULL,
    "Fill Time" DOUBLE NOT NULL,
    "Gross Profit" DOUBLE NOT NULL,
    "Price" NUMERIC(18,4) NOT NULL,
    "Ship Handle Cost" NUMERIC(18,4) NOT NULL,
    "Employee Name" TEXT ENCODING DICT(32) NOT NULL,
    "Employee Dept" TEXT ENCODING DICT(16) NOT NULL,
    "Manager Name" VTEXT ENCODING DICT(32) NOT NULL,
    "Employee Yrs Exp" DOUBLE NOT NULL,
    "Employee Salary" NUMERIC(18,4) NOT NULL,
    "Customer Name" TEXT ENCODING DICT(32) NOT NULL,
    "Customer State" TEXT ENCODING DICT(32) NOT NULL,
    "Call Center Region" TEXT ENCODING DICT(32) NOT NULL,
    "Customer Balance" DOUBLE NOT NULL,
    "Customer Segment" TEXT ENCODING DICT(32) NOT NULL,
    "Prod Type1" TEXT ENCODING DICT(32) NOT NULL,
    "Prod Type2" TEXT ENCODING DICT(32) NOT NULL,
    "Prod Type3" TEXT ENCODING DICT(32) NOT NULL,
    "Prod Type4" TEXT ENCODING DICT(32) NOT NULL,
    "Product Name" TEXT ENCODING DICT(32) NOT NULL,
    "Product Container" TEXT ENCODING DICT(32) NOT NULL,
    "Ship Promo" TEXT ENCODING DICT(32) NOT NULL,
    "Supplier Name" TEXT ENCODING DICT(32) NOT NULL,
    "Supplier Balance" DOUBLE NOT NULL,
    "Supplier Region" TEXT ENCODING DICT(32) NOT NULL,
    "Supplier State" TEXT ENCODING DICT(32) NOT NULL,
    "Order ID" TEXT ENCODING DICT(32) NOT NULL,
    "Order Year" INTEGER NOT NULL,
    "Order Month" INTEGER NOT NULL,
    "Order Day" INTEGER NOT NULL,
    "Order Date" TIMESTAMP NOT NULL,
    "Order Quarter" TEXT ENCODING DICT(8) NOT NULL,
    "Product Base Margin" DOUBLE NOT NULL,
    "Product ID" TEXT ENCODING DICT(32) NOT NULL,
    "Receive Time" DOUBLE NOT NULL,
    "Received Date" TIMESTAMP NOT NULL,
    "Ship Date" TIMESTAMP NOT NULL,
    "Ship Charge" NUMERIC(18,4) NOT NULL,
    "Total Cycle Time" DOUBLE NOT NULL,
    "Product In Stock" TEXT ENCODING DICT(8) NOT NULL,
    "PID" INTEGER NOT NULL,
    "Market Segment" TEXT ENCODING DICT(32) NOT NULL
);
