DROP TABLE IF EXISTS Staples;

CREATE TABLE Staples
(
    "Item Count" INTEGER NOT NULL,
    "Ship Priority" TEXT NOT NULL ENCODING DICT(32),
    "Order Priority" TEXT NOT NULL ENCODING DICT(32),
    "Order Status" TEXT NOT NULL ENCODING DICT(32),
    "Order Quantity" DOUBLE NOT NULL,
    "Sales Total" DOUBLE NOT NULL,
    "Discount" DOUBLE NOT NULL,
    "Tax Rate" DOUBLE NOT NULL,
    "Ship Mode" TEXT NOT NULL ENCODING DICT(32),
    "Fill Time" DOUBLE NOT NULL,
    "Gross Profit" DOUBLE NOT NULL,
    "Price" NUMERIC(18,4) NOT NULL,
    "Ship Handle Cost" NUMERIC(18,4) NOT NULL,
    "Employee Name" TEXT NOT NULL ENCODING DICT(32),
    "Employee Dept" TEXT NOT NULL ENCODING DICT(16),
    "Manager Name" TEXT NOT NULL ENCODING DICT(32),
    "Employee Yrs Exp" DOUBLE NOT NULL,
    "Employee Salary" NUMERIC(18,4) NOT NULL,
    "Customer Name" TEXT NOT NULL ENCODING DICT(32),
    "Customer State" TEXT NOT NULL ENCODING DICT(32),
    "Call Center Region" TEXT NOT NULL ENCODING DICT(32),
    "Customer Balance" DOUBLE NOT NULL,
    "Customer Segment" TEXT NOT NULL ENCODING DICT(32),
    "Prod Type1" TEXT NOT NULL ENCODING DICT(32),
    "Prod Type2" TEXT NOT NULL ENCODING DICT(32),
    "Prod Type3" TEXT NOT NULL ENCODING DICT(32),
    "Prod Type4" TEXT NOT NULL ENCODING DICT(32),
    "Product Name" TEXT NOT NULL ENCODING DICT(32),
    "Product Container" TEXT NOT NULL ENCODING DICT(32),
    "Ship Promo" TEXT NOT NULL ENCODING DICT(32),
    "Supplier Name" TEXT NOT NULL ENCODING DICT(32),
    "Supplier Balance" DOUBLE NOT NULL,
    "Supplier Region" TEXT NOT NULL ENCODING DICT(32),
    "Supplier State" TEXT NOT NULL ENCODING DICT(32),
    "Order ID" TEXT NOT NULL ENCODING DICT(32),
    "Order Year" INTEGER NOT NULL,
    "Order Month" INTEGER NOT NULL,
    "Order Day" INTEGER NOT NULL,
    "Order Date" TIMESTAMP NOT NULL,
    "Order Quarter" TEXT NOT NULL ENCODING DICT(8),
    "Product Base Margin" DOUBLE NOT NULL,
    "Product ID" TEXT NOT NULL ENCODING DICT(32),
    "Receive Time" DOUBLE NOT NULL,
    "Received Date" TIMESTAMP NOT NULL,
    "Ship Date" TIMESTAMP NOT NULL,
    "Ship Charge" NUMERIC(18,4) NOT NULL,
    "Total Cycle Time" DOUBLE NOT NULL,
    "Product In Stock" TEXT NOT NULL ENCODING DICT(8),
    "PID" INTEGER NOT NULL,
    "Market Segment" TEXT NOT NULL ENCODING DICT(32)
);

COPY Staples FROM '/Users/alexb/Projects/omnisci-tableau-connector/tests/TestV1/Staples_utf8.tsv' WITH (delimiter='\t', max_reject=1, quoted='false', header='false');
